module ElasticGraph
  class GraphQL
    module Aggregation
      class FieldTermGroupingSupertype
        attr_reader field_path: fieldPath
        attr_reader missing_value_placeholder: ::String?
        def initialize: (field_path: fieldPath, missing_value_placeholder: ::String?) -> void
        def self.new: (field_path: fieldPath, missing_value_placeholder: ::String?) -> instance | (fieldPath, ::String?) -> instance
      end

      class FieldTermGrouping < FieldTermGroupingSupertype
        include TermGrouping
        include _TermGroupingSubtype
      end
    end
  end
end
